config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :rooms do
    resources :messages, only: %i[new create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  belongs_to :room

  broadcasts_to :room
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  has_many :messages, dependent: :destroy

  broadcasts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :validatable, :trackable, :timeoutable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_room

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.new(message_params)
    @message.assign_attributes(created_by: current_user)

    respond_to do |format|
      if @message.save
        format.turbo_stream
        format.html { redirect_to @room }
      else
        format.turbo_stream
        format.html { render :new }
      end
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: %i[edit update destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.reorder(name: :asc).all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.includes(messages: :created_by).find(params[:id])
    @rooms = Room.reorder(name: :asc).all
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.assign_attributes(created_by: current_user)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mercury</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <%= stylesheet_packs_with_chunks_tag 'application' %>
    <%= javascript_packs_with_chunks_tag 'application' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body class="overflow-hidden">
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<%= content_tag :li, id: dom_id(message) do %>
  <div class="relative pb-8">
    <div class="relative flex items-start space-x-3">
      <div class="relative">
        <div class="h-10 w-10 rounded-full bg-gray-400 flex items-center justify-center ring-8 ring-white"></div>
      </div>
      <div class="min-w-0 flex-1">
        <div>
          <div class="text-sm">
            <a href="#" class="font-medium text-gray-900"><%= message.created_by.email %></a>
          </div>
          <p class="mt-0.5 text-sm text-gray-500">
            <%= message.created_at.to_s(:short) %>
          </p>
        </div>
        <div class="mt-2">
          <div class="prose prose-sm">
            <%== Kramdown::Document.new(message.content, header_offset: 1, input: 'GFM').to_html %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/create.turbo_stream.erb
<%# Note that this does nothing. Rendering is handled by the broadcast. %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= turbo_frame_tag 'new_message', target: '_top' do %>
  <%= form_with(
    class: 'mt-8',
    model: [@message.room, @message],
    data: { controller: 'reset_form', action: 'turbo:submit-end->reset_form#reset' }
  ) do |form| %>
    <div class="flex border border-gray-300 rounded-md shadow">
      <div class="flex-grow focus-within:z-10">
        <%= form.text_area :content,
          placeholder: 'Enter a message...',
          class: 'focus:ring-indigo-500 focus:border-indigo-500 block w-full rounded-none rounded-l-md sm:text-sm border-transparent',
          data: { reset_form_target: 'textarea' } %>
      </div>

      <%= form.submit 'Send', class: '-ml-px relative inline-flex items-center space-x-2 px-4 py-2 border border-transparent text-sm font-medium rounded-r-md text-white bg-green-500 hover:bg-green-400 focus:outline-none focus:ring-2 focus:ring-green-500' %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', @message.room %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<%= link_to room,  id: dom_id(room), class: 'block p-4 w-full font-medium truncate' do %>
  <%= room.name %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="w-0 md:w-56 lg:w-64 bg-white h-screen border-r border-gray-300 shadow hidden md:block">
  <%= render rooms %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= turbo_frame_tag 'room' do %>
  <%= render 'form', room: @room %>
<% end %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="flex">
  <%= render 'rooms/rooms', rooms: @rooms %>

  <div class="overflow-auto flex-grow">
    <div class="container">
      <p class="text-center p-4 text-gray-600 font-medium text-xl">Select a room to get started</p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="flex">
  <%= render 'rooms/rooms', rooms: @rooms %>

  <div class="flex-grow block h-screen overflow-auto" data-controller="room">
    <div class="container">
      <p id="notice"><%= notice %></p>

      <%= turbo_stream_from @room %>

      <%= turbo_frame_tag 'room' do %>
        <div class="flex">
          <div class="flex-grow">
            <%= render @room %>
          </div>

          <div class="p-4 font-medium">
            <%= link_to 'Edit', edit_room_path(@room) %> |
            <%= link_to 'Back', rooms_path, data: { turbo_frame: '_top' } %>
          </div>
        </div>
      <% end %>

      <div class="mt-2 mb-24">
        <div class="-pb-8 p-4 bg-white border border-gray-300 shadow lg:mx-4 lg:rounded-md">
          <ul id="messages">
            <%= render @room.messages %>
          </ul>

          <%= turbo_frame_tag 'new_message', src: new_room_message_path(@room), target: '_top' %>
        </div>
      </div>
    </div>

    <div class="fixed bottom-0 w-full">
      <div class="container"></div>
    </div>
  </div>
</div>